# Generated by Django 3.2.12 on 2023-05-19 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.utils
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("description", models.TextField()),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        db_index=True, default=tasks.utils.datetime_now
                    ),
                ),
                ("executed_at", models.DateTimeField(db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("inprogress", "In Progress"),
                            ("done", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "is_long_running_task",
                    models.BooleanField(default=False, verbose_name="Time Taking Task"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
